In [17]:
# the capital of france is paris

prompt = "the capital of the united states is not "

next_token = " "

output = "the capital of france is paris, "


In [18]:
data = "the capital <pad> <pad> <pad> <pad> "
hedef = "capital of <pad> <pad> <pad> <pad> "

In [19]:
context_length = 12 # gpt-4o 128k, gemma-3-1b 32K

In [20]:
from Tokenizer import Tokenizer

tokenizer = Tokenizer("tokenizer.json")

ids = tokenizer.encode(prompt)

len(ids), ids

(16, [0, 61, 1, 61, 2, 61, 0, 61, 3, 61, 4, 58, 61, 5, 61, 6])

In [30]:
# Load model directly
from transformers import AutoTokenizer, Gemma3ForCausalLM

In [22]:
gemma_tokenizer = AutoTokenizer.from_pretrained("google/gemma-3-1b-it")
gemma_model = Gemma3ForCausalLM.from_pretrained("google/gemma-3-1b-it")

gemma_tokenizer.encode(prompt)

[2, 1437, 5279, 529, 506, 26974, 5022, 563, 711, 236743]

In [23]:
gemma_model

Gemma3ForCausalLM(
  (model): Gemma3TextModel(
    (embed_tokens): Gemma3TextScaledWordEmbedding(262144, 1152, padding_idx=0)
    (layers): ModuleList(
      (0-25): 26 x Gemma3DecoderLayer(
        (self_attn): Gemma3Attention(
          (q_proj): Linear(in_features=1152, out_features=1024, bias=False)
          (k_proj): Linear(in_features=1152, out_features=256, bias=False)
          (v_proj): Linear(in_features=1152, out_features=256, bias=False)
          (o_proj): Linear(in_features=1024, out_features=1152, bias=False)
          (q_norm): Gemma3RMSNorm((256,), eps=1e-06)
          (k_norm): Gemma3RMSNorm((256,), eps=1e-06)
        )
        (mlp): Gemma3MLP(
          (gate_proj): Linear(in_features=1152, out_features=6912, bias=False)
          (up_proj): Linear(in_features=1152, out_features=6912, bias=False)
          (down_proj): Linear(in_features=6912, out_features=1152, bias=False)
          (act_fn): GELUTanh()
        )
        (input_layernorm): Gemma3RMSNorm((1152,), e

In [24]:
girdi = "the letter capital of the united states is not"
cikti = "letter capital of the united states is not london"

In [25]:
with open("text.txt", "r") as f:
  text = f.read()

text

'the capital of the united states is not london. the capital of france is paris, and berlin is the capital of germany. rome is in italy, \n\nmadrid is in spain, and lisbon is in portugal. the capital of the united kingdom is not paris, and the capital of the united states is not berlin. \nalthough these places are often mentioned together, although these capitals are often mentioned together, although these are often mentioned together, \neach country has its own capital, and each country has its own city, and each capital has its own identity, and each capital has its own history. washington \nis the capital of the united states, and london is the capital of the united kingdom. paris is known for art and fashion, and berlin is known for art and \nhistory, and rome is known for art and history, and madrid is known for culture and history, and lisbon is known for culture and art. rome is rich with culture, \nrome is rich with history, rome is rich with art, and madrid is rich with art a

In [26]:
token_ids = tokenizer.encode(text)
# save ids

ids_text = ""

for token_id in token_ids:
  ids_text += f"{token_id} "

with open("token_ids.txt", "w") as f:
  f.write(ids_text)

In [27]:
from text_dataset import create_data_loader

stride = 12

train_data_loader = create_data_loader(token_ids, context_length, stride, 1, False)

len(train_data_loader)

132

In [28]:
i = 0
for batch in enumerate(train_data_loader):
  print(batch)
  i += 1
  if i > 2:
    break

(0, [tensor([[ 0, 61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58]]), tensor([[61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58, 61]])])
(1, [tensor([[61,  5, 61,  6, 61,  7, 59, 61,  0, 61,  1, 61]]), tensor([[ 5, 61,  6, 61,  7, 59, 61,  0, 61,  1, 61,  2]])])
(2, [tensor([[ 2, 61,  8, 61,  5, 61,  9, 60, 61, 10, 61, 11]]), tensor([[61,  8, 61,  5, 61,  9, 60, 61, 10, 61, 11, 61]])])


In [29]:
data_iter = iter(train_data_loader)

In [14]:
next(data_iter)

[tensor([[ 0, 61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58]]),
 tensor([[61,  1, 61,  2, 61,  0, 61,  3, 61,  4, 58, 61]])]

## Embedding yani Sözlük Anlamlarının Sayısal Değerleri
## Eng: Embedding is the numerical representation of the dictionary meanings



In [15]:
the_1 = 0.1
the_2 = 0.4
the_3 = 0.0
the_4 = 0.0

capital_1 = 0.0
capital_2 = 0.2
capital_3 = 0.24
capital_4 = 0.3

of_1 = 0.10
of_2 = 0.04
of_3 = 0.02
of_4 = 0.01

united_1 = 0.30
united_2 = 0.06
united_3 = 0.03
united_4 = 0.01

In [16]:
dict_v1 = [
  [0.1, 0.0, 0.0, 0.0],
  [0.4, 0.2, 0.04, 0.3],
  [0.0, 0.24, 0.02, 0.01],
  [0.0, 0.0, 0.03, 0.01],
  [0.0, 0.0, 0.0, 0.0]
]

dict_v1[0], dict_v1[1], dict_v1[2], dict_v1[3]

([0.1, 0.0, 0.0, 0.0],
 [0.4, 0.2, 0.04, 0.3],
 [0.0, 0.24, 0.02, 0.01],
 [0.0, 0.0, 0.03, 0.01])

In [17]:
dict_v2 = {
  "the": [0.1, 0.0, 0.0, 0.0],
  "capital": [0.4, 0.2, 0.04, 0.3],
  "of": [0.0, 0.24, 0.02, 0.01],
  "united": [0.0, 0.0, 0.03, 0.01],
  "states": [0.0, 0.0, 0.0, 0.0]
}

dict_v2["the"], dict_v2["capital"], dict_v2["of"], dict_v2["united"], dict_v2["states"]

([0.1, 0.0, 0.0, 0.0],
 [0.4, 0.2, 0.04, 0.3],
 [0.0, 0.24, 0.02, 0.01],
 [0.0, 0.0, 0.03, 0.01],
 [0.0, 0.0, 0.0, 0.0])

In [18]:
import plotly.graph_objects as go
import plotly.offline

def plot_dots(sentences_data, title, dims=[0, 1, 2]):
  data = [
    go.Scatter3d(
      x=sentence_data["words"][:, dims[0]],
      y=sentence_data["words"][:, dims[1]],
      z=sentence_data["words"][:, dims[2]],
      mode="markers+text",
      marker=dict(
        size=6,
        color=sentence_data["color"],
      ),
      text=sentence_data["labels"],
      hoverinfo="text",
    ) for sentence_data in sentences_data
  ]

  layout = go.Layout(
    scene=dict(
      xaxis_title="Sertlik",
      yaxis_title="Parlaklık",
      zaxis_title="Kırmızılık",
    ),
    title=title,
  )

  fig = go.Figure(data=data, layout=layout)
  plotly.offline.iplot(fig)



In [19]:
import numpy as np

sentences = [
  {
    "words": np.array([
      [0.1, 0.20, 0.23, 0.0],
      [0.4, 0.2, 0.04, 0.3],
      [0.12, 0.24, 0.2, 0.01],
      [0.0, 0.0, 0.3, 0.01],
      [0.0, 0.0, 0.0, 0.0]
    ]),
    "labels": ["the", "capital", "of", "united", "states"],
    "color": "red",
  },
  {
    "words": np.array([
      [0.4, 0.2, 0.04, 0.3],
      [0.12, 0.24, 0.2, 0.01],
      [0.0, 0.0, 0.3, 0.01],
      [0.0, 0.0, 0.0, 0.0]
    ]),
    "labels": ["capital", "of", "united", "states"],
    "color": "blue",
  }
]

plot_dots(sentences, "Sözlük V1")

In [20]:
import torch

embeddings = torch.nn.Embedding(num_embeddings=64, embedding_dim=4)

In [21]:
sentence = "the capital of united states and the capital of france"

In [22]:
tokens = tokenizer.encode(sentence)
tokens

[0, 61, 1, 61, 2, 61, 3, 61, 4, 58, 61, 10, 61, 0, 61, 1, 61, 2, 61, 8]

In [23]:
meanings = embeddings(torch.tensor(tokens))
meanings

tensor([[ 1.1154, -0.5703,  0.2771, -0.1869],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [ 0.7331,  0.3086,  1.1211, -0.1848],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [-0.9732,  1.1379, -0.2816,  0.1303],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [ 0.7279,  0.5921,  0.7281,  1.1609],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [ 0.7003, -1.0178, -0.2777, -0.9438],
        [-1.3724,  0.2090,  0.3724, -0.8869],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [-1.2150, -0.1916,  0.7711,  0.0236],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [ 1.1154, -0.5703,  0.2771, -0.1869],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [ 0.7331,  0.3086,  1.1211, -0.1848],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [-0.9732,  1.1379, -0.2816,  0.1303],
        [ 0.0688, -0.5170, -0.4220, -1.8070],
        [ 0.3460,  0.1245, -0.4094, -1.5352]], grad_fn=<EmbeddingBackward0>)

In [24]:
sentences = [
  {
    "words": meanings.detach().numpy(),
    "labels": tokenizer.tokenize(sentence),
    "color": "red",
  },
]
plot_dots(sentences, "Sözlük V1")

In [25]:
gemma_tokens = gemma_tokenizer.encode(sentence)
gemma_tokens

[2, 1437, 5279, 529, 26974, 5022, 532, 506, 5279, 529, 61034]

In [26]:
gemma_model.model.embed_tokens(torch.tensor(gemma_tokens))

tensor([[ 0.0041, -0.0064, -0.0159,  ..., -0.0073,  0.0008,  0.0037],
        [-0.0049,  0.0376,  0.0233,  ...,  0.0193,  0.0347, -0.0144],
        [ 0.0238,  0.0139,  0.0168,  ...,  0.0151, -0.0094, -0.0076],
        ...,
        [ 0.0238,  0.0139,  0.0168,  ...,  0.0151, -0.0094, -0.0076],
        [ 0.0112,  0.0077,  0.0023,  ...,  0.0006,  0.0002,  0.0173],
        [ 0.0054,  0.0310,  0.0006,  ..., -0.0059, -0.0140, -0.0520]],
       grad_fn=<EmbeddingBackward0>)

In [27]:
gemma_meanings = gemma_model.model.embed_tokens(torch.tensor(gemma_tokens))
gemma_meanings.shape

torch.Size([11, 1152])

In [28]:
gemma_tokenizer.tokenize(sentence)

['the',
 '▁capital',
 '▁of',
 '▁united',
 '▁states',
 '▁and',
 '▁the',
 '▁capital',
 '▁of',
 '▁france']

In [29]:
gemma_sentences = [
  {
    "words": gemma_meanings.detach().numpy(),
    "labels": gemma_tokenizer.tokenize(sentence),
    "color": "red",
  },
]
plot_dots(gemma_sentences, "Gemma", dims=[20, 21, 22])